openapi: '3.0.3'
info:
  version: 1.0.0
  title: Object Store Database Endpoints
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: christophhagelkruys@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:8080/objects/v1
    description: Local server

paths:
  '/types/{id}/objects':
    get:
      summary: Get all Objects for specified Type
      tags:
        - objects
      operationId: getObjectsById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ObjectsResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
    post:
      summary: Create Object for specified Type
      tags:
        - objects
      operationId: createObjectById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Object'
      responses:
        '200':
          $ref: '#/components/responses/ObjectResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  '/types/{id}/objects/{objectId}':
    get:
      summary: Get Object by type and objectId
      tags:
        - objects
      operationId: getObjectById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: objectId
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ObjectResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
    put:
      summary: Update Object by type and objectId
      tags:
        - objects
      operationId: updateObjectById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: objectId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Object'
      responses:
        '200':
          $ref: '#/components/responses/ObjectResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
    delete:
      summary: Delete Object by type and objectId
      tags:
        - objects
      operationId: deleteObjectById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: objectId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError


components:
  schemas:
    Object:
      type: object
      additionalProperties: true
  responses:
    ObjectsResponse:
      description: An array of objects defined by type
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Object'
    ObjectResponse:
      description: Requested Object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Object'

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
