CREATE TABLE IF NOT EXISTS TYPE (
    ID uuid NOT NULL,
    NAME VARCHAR NOT NULL,
    ADDITIONAL_PROPERTIES BOOLEAN NOT NULL,
    BACKEND_KEY_DEFINITIONS jsonb not null,
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS BACKEND_KEY_DEFINITION (
    ID uuid NOT NULL,
    TYPE_DOCUMENT_ID uuid NOT NULL,
    KEY VARCHAR NOT NULL,
    TYPE VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_type FOREIGN KEY(TYPE_DOCUMENT_ID) REFERENCES TYPE(ID)
);